title: Jekyll AsciiDoc Action
description: A GitHub Action to publish AsciiDoc content as a GitHub Pages site
author: Alain Helaili
email: helaili@github.com
source: sample_site
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
