name: Testing the GitHub Pages publication

on:
  push
    
env:
  URL: https://helaili.github.io/jekyll-action/

jobs:
  
  basic-publish: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-\
    - name: Basic run
      uses: ./
      with:
        jekyll_build_options: "--config ../sample_site/config.yml,../sample_site/_config_basic.yml"
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
      
  basic-test: 
    runs-on: ubuntu-latest
    needs: basic-publish
    steps:
    - uses: actions/checkout@v2
    - name: Caching
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Cypress run
      uses: cypress-io/github-action@v2.7.2
      with:
        config: baseUrl=https://helaili.github.io
        working-directory: tests/e2e
    - name: Save Cypress Screenshots
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-screenshots-${{ runner.os }}-${{ matrix.node-version }}
        path: tests/e2e/screenshots
      # Test run video was always captured, so this action uses "always()" condition
    - name: Save Cypress Videos
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-videos-${{ runner.os }}-${{ matrix.node-version }}
        path: tests/e2e/videos
